"""empty message

Revision ID: de5741c2f1e3
Revises: 4d93a6afef48
Create Date: 2019-09-25 19:23:44.711821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de5741c2f1e3'
down_revision = '4d93a6afef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.drop_column('answer', 'author_ID')
    op.add_column('answer', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_1', 'answer', 'user', ['author_ID'], ['id'])
    op.drop_column('answer', 'author_id')
    # ### end Alembic commands ###

